### ISSUE TITLE
Unable to copy/paste into dashboard UI

### ISSUE THREAD

**Issue by eric-engberg** [grafana/grafana-vs-code-extension#73] opened 2024-01-12 20:41 UTC
I was trying to copy/paste a query into the vscode panel but there's no ability to paste into the panel.

**Comment by hd-deman** [comment] 2024-02-15 19:03
same for me. Mac OS vscode  1.86.2

**Comment by hd-deman** [comment] 2024-02-16 10:46
VS code has an existing/known issue with the Copy/Paste which appears on right click. This issue is present for all VS Code plugins which uses web view.

**Issue Reported on GitHub:**  [Context-Menu COPY is not working in vscode webview, BUT ctrl+c is working fine · Issue #141080 · microsoft/vscode](https://github.com/microsoft/vscode/issues/141080)

**VS Code Release Updates**: https://code.visualstudio.com/updates/v1_57#_context-menus-for-webviews

**Comment by K-Phoen** [comment] 2024-09-24 14:34
Is this still true with the latest version? I couldn't reproduce this issue.

**Comment by K-Phoen** [comment] 2024-10-14 13:23
Closing this. Feel free to reopen an issue if the problem persists :)

**Closed by K-Phoen** 2024-10-14 13:23 UTC
